services:
  travel-app-prod:
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: "${PROD_APP_NAME}:${PROD_APP_VERSION}"
    container_name: "${PROD_APP_NAME}"
    networks:
      - frontend
    ports:
      - "${PROD_APP_PORT}:80"
    environment:
      PRODUCTION: true

networks:
  frontend:
    name: "${PROD_APP_NAME}"
    driver: bridge
