services:
  travel-app-dev:
    env_file: .env
    build: .
    image: "${DEV_APP_NAME}:${DEV_APP_VERSION}"
    container_name: "${DEV_APP_NAME}"
    networks:
      - frontend
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: frontend
        target: /app/node_modules
    ports:
      - "${DEV_APP_PORT}:8080"
    environment:
      DEBUG: true
    command: npm run dev

networks:
  frontend:
    name: "${DEV_APP_NAME}"
    driver: bridge

volumes:
  frontend:
    name: "${DEV_APP_NAME}"
