services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - "3000:8080"
    environment:
      DEBUG: 'true'
    command: "npm run dev"
