services:
  app:
    build:
      context: .
      dockerfile: ./production.Dockerfile
    ports:
      - "3001:8080"
    environment:
      PRODUCTION: 'true'
    command: "npm run preview"
