services:
  travel:
    image: node:18.14.2-alpine3.17
    container_name: travel
    working_dir: /usr/src/app
    volumes:
      - ../:/usr/src/app
    ports:
      - 3001:8080
    entrypoint:
      - sh
      - -c
      - |
        npm i
        npm run dev
    restart: unless-stopped
    mem_reservation: 128m
    mem_limit: 256m
    cpus: 0.50 # 50% of CPU
    cpuset: "0" # Use only the first CPU
