apiVersion: v1
kind: Service
metadata:
  name: travel-svc
  namespace: web
  labels:
    app: travel
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    app: travel
